### ISSUE TITLE
Conflict with jquery

### ISSUE THREAD

**Issue by evreninanc** [stuartjnelson/badger-accordion#1]
Hello, badger accordion prevents jquery scripts from running, like jquery modal (http://jquerymodal.com), mega-menu (https://codepen.io/riogrande/pen/MKXweV)

**Comment by stuartjnelson** [comment]
Hello Evren,

Thanks for getting in touch. So I can investigate this further please could you give me some more info. I have just added an _Issue template_ that outlines how Ideally I'd like issues logged. When I've got some more information I'll hopefully be able to help you debug this.

Thanks again for getting in touch. Look forward to hearing from you.
Stuart



# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by evreninanc** [comment]
# Expected Behavior

Here is a working example of Mega-Menu: http://haylazrobot.e-hamal.com/siteRoot-HTML/sepet2.html

# Current Behavior

Here is the page with accordion added, Mega-Menu not working: http://haylazrobot.e-hamal.com/siteRoot-HTML/sepet1.html

# Context

Firmware Version:
Operating System: macOS High Sierra 10.13.2
SDK version:
Toolchain version:

**Comment by stuartjnelson** [comment]
Hi Evren,

Thanks for giving me the extra info. The links were really helpful. I had a look at the plugin and think I have fixed the issue. I created a little [Codepen](https://codepen.io/stuartjnelson/pen/eyOZNW) that included he jQuery modal you mentioned in your initial comment. If you update the plugin I hope this should fix your issue. Can you let me know either way if this fixes the bug on your site. 

Thanks!
Stuart

**Comment by evreninanc** [comment]
Thank you Stuart, modal works now. Unfortunately megamenu is still not working on pages with accordion function. You may find the js file attached. I would really appreciate if you could take a look to that file also.

[megamenu.js.zip](https://github.com/stuartjnelson/badger-accordion/files/1550815/megamenu.js.zip)

**Comment by stuartjnelson** [comment]
Hi Evren,

I have just pushed an update that should fix the error you are getting with badger-accordion. If you look in your console there are a host of errors on the link you supplied above (on both the version with and without the accordion). I think in best interests of keeping the thread clean could you try update the accordion and deploy the code to `sepet1.html`. If I can see the error is fixed there I'm happy to have a look at some of the other errors that are unrelated to the accordion. 

<br>

**Other Errors**
As you can see here are the errors on the link without the accordion. 
<img width="763" alt="screen shot 2017-12-12 at 10 30 34" src="https://user-images.githubusercontent.com/5795894/33901716-8db74562-df27-11e7-92d1-7c8975e1040c.png">


1. Put your all your `<scripts>` just before the closing `</body>` tag. You need to ensure that any of them that use jQuery are included _after_ jQuery. Currently both the scripts below have been included before jQuery so hence ;

```
<script src="js/script.js?v=1278964" charset="UTF-8"></script>
<script src="js/global.js?v=454346456"></script>
```


2. My guess with the modal issue here is you are missing some markup


3. I think the issue with `megamenu.js` is that you have added an extra _k_ to your variable for jQuery.

Current
```
/*global $k */
var $kk = jQuery.noConflict();
$k(document).ready(function () {
```

Try updating to
```
/*global $k */
var $k = jQuery.noConflict();
$k(document).ready(function () {
```


4. As to this issue;
<img width="710" alt="screen shot 2017-12-12 at 10 34 10" src="https://user-images.githubusercontent.com/5795894/33901873-042e062c-df28-11e7-9365-96b8e753d092.png"> my guess is that you are also missing markup.


Hope this helps. If you're still getting issues please update your staging links and I can take a look.

**Comment by stuartjnelson** [comment]
Hi Evren,

I'm not sure right now whats going on. I have a [demo](https://codepen.io/stuartjnelson/pen/eyOZNW?editors=1000) (its ugly but functional) where I have the megamenu, modal & accordion without without any errors. Could you try jQuery in noConflict mode like I have in the demo? The issue im happy to say that the accordion now does not seem to be causing any issues so im going to close this issue. Feel free to email me if you want any future help with your site.

Thanks!
Stuart
